### ISSUE TITLE
I don't know why but program can't find the resolution of the game. Default value works fine.

### ISSUE THREAD

**Issue by Daloshka** [scogliera/csgo-autoaccept#5]

**Comment by samcannas** [comment]
Sorry for the late response, could you provide me with your in-game resolution? The program detects the resolution only if you're using fullscreen stretched. If the CS:GO resolution doesn't change the display resolution (For example when you're using 1920x1080 on desktop, but also in CS), the program won't detect it and it will use your display resolution.

**Comment by samcannas** [comment]
When using the default value (your screen resolution), the program scans the whole screen for the accept button, making it slower, but should always work

**Comment by Daloshka** [comment]
I tested it with 1920x1080 (desktop and in the game). Fullscreen mode. I think it isn't stretched. Btw thanks for replies

**Comment by samcannas** [comment]
If you have the same resolution for your desktop and in-game, the program won't detect the resolution, because it's waiting for the monitor to change resolutions (for example 1920x1080 on desktop, but 1280x720 when you open the game). So when you're using 1920x1080 on both, it will just use 1920x1080.

Thank you for creating an issue and be sure to let me know when if you find other bugs!
